# This file was generated by GoReleaser. DO NOT EDIT.
cask "sekd" do
  version "0.2.1"

  on_macos do
    on_intel do
      url "https://github.com/jefrnc/sekd/releases/download/v#{version}/sekd_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/jefrnc/sekd"
      sha256 "97ee025e3209bbd325ef9e3d5103976297cd03610e18360216bf14896ae4abbe"
    end
    on_arm do
      url "https://github.com/jefrnc/sekd/releases/download/v#{version}/sekd_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/jefrnc/sekd"
      sha256 "3cdf7ea419ab468ff4aee705c8e2d42d6b2e7cf659ec25db8a111b6ab304ba47"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jefrnc/sekd/releases/download/v#{version}/sekd_#{version}_linux_amd64.tar.gz",
        verified: "github.com/jefrnc/sekd"
      sha256 "ddbb918e193d0a4b9d3aeabb2c3781134436b1c79b645b9d69b74875989f7f5a"
    end
    on_arm do
      url "https://github.com/jefrnc/sekd/releases/download/v#{version}/sekd_#{version}_linux_arm64.tar.gz",
        verified: "github.com/jefrnc/sekd"
      sha256 "ef59b607bbcf317270a090d19a2c833c076bf54ff3d711faf7c6ea67c3950511"
    end
  end

  name "sekd"
  desc "Day-trading due diligence in your terminal — SEC filings, dilution risk, and AI extraction"
  homepage "https://github.com/jefrnc/sekd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sekd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sekd"]
    end
  end

  # No zap stanza required

end
