# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sekd < Formula
  desc "Day-trading due diligence in your terminal — SEC filings, dilution risk, and AI extraction"
  homepage "https://github.com/jefrnc/sekd"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jefrnc/sekd/releases/download/v0.2.0/sekd_0.2.0_darwin_amd64.tar.gz"
      sha256 "3021f3138f80380d19fd6e54f4802dc631bb241800683a24c1839ccb60fa4f12"

      define_method(:install) do
        bin.install "sekd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jefrnc/sekd/releases/download/v0.2.0/sekd_0.2.0_darwin_arm64.tar.gz"
      sha256 "d0e50113231aac52db813fd8480a5e1aa78efe2be9653ac15b7097be1206ab27"

      define_method(:install) do
        bin.install "sekd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jefrnc/sekd/releases/download/v0.2.0/sekd_0.2.0_linux_amd64.tar.gz"
      sha256 "9cf2d0a74d6747f77b27f2026f9c28420e680fcdc8551cebc5f24c0b4b907c86"
      define_method(:install) do
        bin.install "sekd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jefrnc/sekd/releases/download/v0.2.0/sekd_0.2.0_linux_arm64.tar.gz"
      sha256 "5a10018f54fbea1db8e66994b5278af93d7030fa83d8bc9caf69aae458dd75db"
      define_method(:install) do
        bin.install "sekd"
      end
    end
  end

  test do
    system bin/"sekd", "version"
  end
end
